#
###################################
# Site wide configuration
####################################
#
title: Sungyong Seo @ USC
email:
description: Personal page of Sungyong Seo
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Sungyong Seo
  avatar: sungyong-linkedin.jpg
  job: "Computer Science Ph.D. student @ USC"
  bio: "<b>Research Interests</b> <br> Graph Networks <br>Physics-informed Learning<br> Spatiotemporal models"
  email: #
  disqus-shortname:
  twitter: seo_sseo
  facebook: #s.sungyong
  googlescholar: sungyong seo
  google: 
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sungyongs
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sungyongs
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

# Google Analytics
google_analytics: UA-134151837-1